# Generated by Django 2.1.7 on 2019-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banquet_name', models.CharField(max_length=700, verbose_name='バンケット名')),
                ('banquet_description', models.CharField(max_length=700, verbose_name='バンケットの紹介文')),
                ('banquet_image', models.CharField(max_length=700, verbose_name='バンケットの画像')),
                ('banquet_base_cost', models.IntegerField(verbose_name='バンケットの基本費用')),
                ('banquet_cost_per_table', models.IntegerField(verbose_name='テーブル1卓当たりの費用')),
                ('banquet_cost_per_guest', models.IntegerField(verbose_name='ゲスト1人当たりの費用')),
                ('banquet_guest_per_table', models.IntegerField(verbose_name='テーブル1卓当たりのゲスト人数')),
                ('banquet_min_guests', models.IntegerField(verbose_name='対応可能な最小ゲスト人数')),
                ('banquet_max_guests', models.IntegerField(verbose_name='対応可能な最大ゲスト人数')),
            ],
            options={
                'verbose_name': 'バンケット',
                'verbose_name_plural': 'バンケット',
                'db_table': 'banquet',
            },
        ),
        migrations.CreateModel(
            name='BeforePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo_name', models.CharField(max_length=700, verbose_name='前撮りサービス名')),
                ('before_photo_description', models.CharField(max_length=700, verbose_name='前撮りサービスの紹介文')),
                ('party_costume_image', models.CharField(max_length=700, verbose_name='前撮りサービスの画像')),
                ('before_photo_cost', models.IntegerField(verbose_name='一式費用')),
            ],
            options={
                'verbose_name': '前撮りサービス',
                'verbose_name_plural': '前撮りサービス',
                'db_table': 'before_photo',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_cost', models.IntegerField(verbose_name='ウエディングケーキの基本費用')),
                ('cake_min_guest', models.IntegerField(verbose_name='このデータの金額になる最少人数')),
                ('cake_max_guest', models.IntegerField(verbose_name='このデータの金額になる最大人数')),
            ],
            options={
                'verbose_name': 'ウエディングケーキ',
                'verbose_name_plural': 'ウエディングケーキ',
                'db_table': 'cake',
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_name', models.CharField(max_length=700, verbose_name='コーディネート名')),
                ('coordinate_description', models.CharField(max_length=700, verbose_name='コーディネートの紹介文')),
                ('coordinate_image', models.CharField(max_length=700, verbose_name='コーディネートの画像')),
                ('coordinate_base_cost', models.IntegerField(verbose_name='基本費用')),
                ('coordinate_cost_per_guest', models.IntegerField(verbose_name='1卓当たりの費用')),
            ],
            options={
                'verbose_name': 'コーディネート',
                'verbose_name_plural': 'コーディネート',
                'db_table': 'coordinate',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=700, verbose_name='お料理名')),
                ('cuisine_description', models.CharField(max_length=700, verbose_name='お料理の紹介文')),
                ('cuisine_image', models.CharField(max_length=700, verbose_name='お料理の画像')),
                ('cuisine_cost_per_guest', models.IntegerField(verbose_name='ゲスト1人当りの費用')),
            ],
            options={
                'verbose_name': 'お料理',
                'verbose_name_plural': 'お料理',
                'db_table': 'cuisine',
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_name', models.CharField(max_length=700, verbose_name='演出名')),
                ('effect_description', models.CharField(max_length=700, verbose_name='演出の紹介文')),
                ('effect_image', models.CharField(max_length=700, verbose_name='演出の画像')),
                ('effect_base_cost', models.IntegerField(verbose_name='全体の費用')),
                ('effect_cost_per_table', models.IntegerField(verbose_name='1卓当たりの費用')),
                ('effect_cost_per_guest', models.IntegerField(verbose_name='ゲスト1人当たりの費用')),
            ],
            options={
                'verbose_name': '演出',
                'verbose_name_plural': '演出',
                'db_table': 'effect',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=700, verbose_name='記録ムービーサービス名')),
                ('movie_description', models.CharField(max_length=700, verbose_name='記録ムービーサービスの紹介文')),
                ('movie_image', models.CharField(max_length=700, verbose_name='記録ムービーサービスの画像')),
                ('movie_cost', models.IntegerField(verbose_name='一式費用')),
            ],
            options={
                'verbose_name': '記録ムービーサービス',
                'verbose_name_plural': '記録ムービーサービス',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='PartyCostume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_costume_name', models.CharField(max_length=700, verbose_name='パーティ衣装スタイル名')),
                ('party_costume_description', models.CharField(max_length=700, verbose_name='パーティ衣装スタイルの紹介文')),
                ('party_costume_image', models.CharField(max_length=700, verbose_name='パーティ衣装の画像')),
                ('party_costume_cost1', models.IntegerField(verbose_name='パーティ衣装スタイル種別が挙式スタイル種別と同じ場合の費用')),
                ('party_costume_cost2', models.IntegerField(verbose_name='パーティ衣装スタイル種別が挙式スタイル種別と違う場合の費用')),
                ('party_costume_type', models.IntegerField(choices=[(0, '和装'), (1, '洋装')], verbose_name='スタイル種別')),
            ],
            options={
                'verbose_name': 'パーティ衣装スタイル',
                'verbose_name_plural': 'パーティ衣装スタイル',
                'db_table': 'party_costume',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=700, verbose_name='フォト・記念サービス名')),
                ('photo_description', models.CharField(max_length=700, verbose_name='フォト・記念サービスの紹介文')),
                ('party_costume_image', models.CharField(max_length=700, verbose_name='フォト・記念サービスの画像')),
                ('photo_cost', models.IntegerField(verbose_name='一式費用')),
            ],
            options={
                'verbose_name': 'フォト・記念サービス',
                'verbose_name_plural': 'フォト・記念サービス',
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=700, verbose_name='会場名')),
            ],
            options={
                'verbose_name': '会場',
                'verbose_name_plural': '会場',
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=700, verbose_name='挙式スタイル名')),
                ('style_description', models.CharField(max_length=700, verbose_name='挙式スタイルの紹介文')),
                ('style_image', models.CharField(max_length=700, verbose_name='挙式スタイルの画像')),
                ('style_cost', models.IntegerField(verbose_name='費用')),
                ('style_type', models.IntegerField(choices=[(0, '和装'), (1, '洋装')], verbose_name='スタイル種別')),
                ('site', models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場')),
            ],
            options={
                'verbose_name': '挙式スタイル',
                'verbose_name_plural': '挙式スタイル',
                'db_table': 'style',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='partycostume',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='movie',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='effect',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='cake',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='beforephoto',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
        migrations.AddField(
            model_name='banquet',
            name='site',
            field=models.ForeignKey(on_delete=False, to='api.Site', verbose_name='会場'),
        ),
    ]
