# Generated by Django 2.1.7 on 2019-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=10, verbose_name='名字')),
                ('first_name', models.CharField(max_length=10, verbose_name='名前')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
