# Generated by Django 2.1.7 on 2019-03-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='姓')),
                ('last_name', models.CharField(max_length=15, verbose_name='名')),
                ('first_name_kana', models.CharField(max_length=30, verbose_name='セイ（Last kana）')),
                ('last_name_kana', models.CharField(max_length=30, verbose_name='メイ（First kana）')),
                ('tel', models.CharField(default=None, max_length=15, null=True, verbose_name='電話番号')),
                ('mail', models.CharField(default=None, max_length=15, null=True, verbose_name='メール')),
                ('place', models.CharField(default=None, max_length=15, null=True, verbose_name='会場名')),
                ('appoint_date', models.DateField(default=None, null=True, verbose_name='来館予定日')),
                ('appoint_status', models.IntegerField(choices=[('調整中', '0'), ('確定', '1')], verbose_name='予約ステータス')),
                ('link', models.CharField(default=None, max_length=15, null=True, verbose_name='リンク発行')),
            ],
            options={
                'verbose_name': '顧客情報',
                'verbose_name_plural': '顧客情報',
                'db_table': 'client',
            },
        ),
    ]
