# Generated by Django 2.1.7 on 2019-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='site_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='会場ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='test_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ABテストパターン(A/B)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='appoint_status',
            field=models.IntegerField(choices=[(0, '調整中'), (1, '確定')], verbose_name='予約ステータス'),
        ),
    ]
