# Generated by Django 2.1.7 on 2019-03-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190303_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=700, verbose_name='URL')),
                ('description', models.CharField(max_length=700, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('client', models.ForeignKey(on_delete=False, to='app.Client')),
            ],
        ),
    ]
